
export const downloadFile = (filename: string, content: string, mimeType: string = 'text/plain') => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const generateQuotationText = (quo: any, companyInfo: { name: string, address: string }) => {
  const lineItems = quo.items.map((item: any) => 
    `${item.productName.padEnd(30)} | Qty: ${item.quantity.toString().padEnd(5)} | Price: $${item.unitPrice.toFixed(2).padEnd(8)} | Total: $${item.total.toFixed(2)}`
  ).join('\n');

  return `
================================================================================
${companyInfo.name.toUpperCase()}
${companyInfo.address}
================================================================================
OFFICIAL SALES QUOTATION
--------------------------------------------------------------------------------
Quote ID: ${quo.id}
Date: ${quo.date}
Expiry: ${quo.expiryDate}
--------------------------------------------------------------------------------
CUSTOMER INFORMATION:
Name: ${quo.customerName}
Customer ID: ${quo.customerId}
--------------------------------------------------------------------------------
LINE ITEMS:
${lineItems}
--------------------------------------------------------------------------------
GRAND TOTAL: $${quo.totalAmount.toLocaleString()}
--------------------------------------------------------------------------------
NOTES:
This quotation is valid for 30 days. Prices are inclusive of applicable 
pharmaceutical taxes. 

Authorized Signature: _________________________  Date: ______________
================================================================================
Generated by PharmaFlow CRM
`;
};

export const generateIisInstallationGuide = (companyName: string) => {
  return `
PHARMAFLOW CRM - ENTERPRISE IIS INSTALLATION & DEPLOYMENT GUIDE
Prepared for: ${companyName}
Generated on: ${new Date().toLocaleString()}
Document Version: 2.1.0-STABLE
--------------------------------------------------------------------------------

1. SYSTEM PREREQUISITES
================================================================================
- Windows Server 2016 / 2019 / 2022
- Internet Information Services (IIS) 10.0+
- IIS URL Rewrite Module 2.1 (MANDATORY)
  Download: https://www.iis.net/downloads/microsoft/url-rewrite

2. SERVER CONFIGURATION STEPS
================================================================================
STEP A: INSTALL URL REWRITE
Install the URL Rewrite module. Without this, clicking refresh or navigating 
manually to sub-pages (like /inquiries) will result in a 404 error.

STEP B: CREATE THE APPLICATION POOL
1. Open IIS Manager.
2. Right-click 'Application Pools' -> 'Add Application Pool'.
3. Name: "PharmaFlowAppPool"
4. .NET CLR Version: "No Managed Code"
5. Managed Pipeline Mode: "Integrated"

STEP C: PHYSICAL PATH & PERMISSIONS
1. Extract the production build (the 'dist' folder) to a secure location, 
   e.g., C:\\inetpub\\wwwroot\\PharmaFlow
2. Ensure the 'IIS_IUSRS' group has Read & Execute permissions on this folder.

STEP D: SITE CREATION
1. Right-click 'Sites' -> 'Add Website'.
2. Site Name: "PharmaFlowCRM"
3. Physical Path: C:\\inetpub\\wwwroot\\PharmaFlow
4. Binding: Set your preferred Port (80/443) and Hostname.

3. WEB.CONFIG VALIDATION
================================================================================
The root directory MUST contain a web.config file. A pre-configured file is 
included in this deployment package. It handles:
- SPA Routing (Redirects all non-file requests to index.html)
- Modern MIME Types (woff2, mjs, json)
- Security Headers (nosniff, Cache-Control)

4. DATABASE CONNECTIVITY
================================================================================
The app is currently in 'Mock Mode'. To connect to a live SQL Server/PostgreSQL:
1. Navigate to the Admin Panel -> System Data.
2. Download the 'SQL Schema Script'.
3. Execute the script on your database server.
4. Update the DB Host in the Admin Panel to point to your secure API endpoint.

5. TROUBLESHOOTING
================================================================================
Q: I see a "Unexpected token <" error in the console.
A: The URL Rewrite module is likely not installed or the web.config is missing.

Q: Icons are not appearing.
A: Ensure the .woff2 MIME type is added in IIS (it is included in web.config).

--------------------------------------------------------------------------------
SUPPORT & MAINTENANCE:
For technical assistance, please contact the System Administrator at:
deployment-support@pharmaflow-enterprise.com
================================================================================
`;
};
